POST http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzUwMjUyMDE3LCJ1c2VySWQiOjF9.I_SNb0ePjUeW73ewgDhtTWlQBL2hu6kGrc3AKncpc1E
