PUT http://localhost:8080/events/1
content-type: application/json

{
  "name": "Test event updated",
  "description": "A test event",
  "location": "A test location (updated)",
  "dateTime": "2025-01-02T15:30:00.000Z"
}